name: hangman
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+4005

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rflutter_alert: ^1.0.3
  material_design_icons_flutter: ^3.2.4495
  sqflite: ^1.3.0
  path: ^1.6.4
  flutter_spinkit: ^4.1.2
  date_format: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - images/
    - res/
  fonts:
    - family: PatrickHand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Bold.ttf
        - asset: fonts/FiraMono-Regular.ttf